server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/identityservice"
    username: postgres
    password: change_this_password_on_production
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${JWT_SIGNER_KEY}
